// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmms9SSsXdcSC1j-MdJ4mQLe7cl8QG-qQ',
    appId: '1:251823266093:web:41940ee093c7ff9b505ba4',
    messagingSenderId: '251823266093',
    projectId: 'personal-salon-app',
    authDomain: 'personal-salon-app.firebaseapp.com',
    storageBucket: 'personal-salon-app.firebasestorage.app',
    measurementId: 'G-71VV40HS06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKyYxH7cGashZwS_nwBN9KbLi49JhOFEE',
    appId: '1:251823266093:android:010100d00e8634c5505ba4',
    messagingSenderId: '251823266093',
    projectId: 'personal-salon-app',
    storageBucket: 'personal-salon-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKsEJsx_EebJwt2pfp1TzzAt0x1L9kG40',
    appId: '1:251823266093:ios:c0e4df08d6c2c7c1505ba4',
    messagingSenderId: '251823266093',
    projectId: 'personal-salon-app',
    storageBucket: 'personal-salon-app.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKsEJsx_EebJwt2pfp1TzzAt0x1L9kG40',
    appId: '1:251823266093:ios:c0e4df08d6c2c7c1505ba4',
    messagingSenderId: '251823266093',
    projectId: 'personal-salon-app',
    storageBucket: 'personal-salon-app.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmms9SSsXdcSC1j-MdJ4mQLe7cl8QG-qQ',
    appId: '1:251823266093:web:827c9d7d1239a004505ba4',
    messagingSenderId: '251823266093',
    projectId: 'personal-salon-app',
    authDomain: 'personal-salon-app.firebaseapp.com',
    storageBucket: 'personal-salon-app.firebasestorage.app',
    measurementId: 'G-VK4KWE17X3',
  );
}
